name: 'Rust Release'
description: 'Create a github release from version in Cargo.toml on push to main'
inputs:
  owner:
    description: 'Github Repo Owner'
    required: true
    default:  ${{ github.repository_owner }}
  repo:
    description: 'Github Repo'
    required: true
    default: ${{ github.repository }}
  token:
    description: 'Github Token'
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}
  cargo:
    description: 'Cargo.toml path'
    required: true
    default: 'Cargo.toml'
outputs:
  version:
    description: 'The Release Tag'
runs:
  using: 'node16'
  main: 'dist/index.js'