name: "Rust Release"
description: "Create a github release from version in Cargo.toml on push to main"
inputs:
  tag_prefix:
    description: "Tag prefix"
    required: true
  owner:
    description: "Github Repo Owner"
    default: ${{ github.repository_owner }}
    required: true
  repo:
    description: "Github Repo"
    default: ${{ github.repository }}
    required: true
  token:
    description: "Github Token"
    required: true
  cargo:
    description: "Cargo.toml path"
    required: true
    default: "Cargo.toml"
  commit_sha:
    description: "SHA1 of the commit to tag"
    default: ${{ github.sha }}
    required: true
outputs:
  version:
    description: "The version in the Cargo.toml"
  is_new_version:
    description: "If the version is new"
  tag_name:
    description: "Name of the tag"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: box
  color: gray-dark
