name: "Rust Release"
description: "Create a github release from version in Cargo.toml on push to main"
inputs:
  title:
    description: "Release prefix title"
    required: true
  owner:
    description: "Github Repo Owner"
    required: true
  repo:
    description: "Github Repo"
    required: true
  token:
    description: "Github Token"
    required: true
  cargo:
    description: "Cargo.toml path"
    required: true
    default: "Cargo.toml"
  dry_run:
    description: "do not actually create release"
    required: true
    default: "false"
outputs:
  version:
    description: "The version in the Cargo.toml"
  created_new_release:
    description: "Did the action create a new release?"
  release_name:
    description: "The name of the generated release"
  release_id:
    description: "The generated release id if a release was created, otherwise null"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: box
  color: gray-dark
