name: "Rust Release"
description: "Create a github release from version in Cargo.toml on push to main"
inputs:
  title:
    description: "Tag prefix"
    required: true
  owner:
    description: "Github Repo Owner"
    default: ${{ github.repository_owner }}
    required: true
  repo:
    description: "Github Repo"
    default: ${{ github.repository }}
    required: true
  token:
    description: "Github Token"
    default: ${{ secrets.GITHUB_TOKEN }}
    required: true
  cargo:
    description: "Cargo.toml path"
    required: true
    default: "Cargo.toml"
  dry_run:
    description: "do not actually create release"
    required: true
    default: "false"
  commit_sha:
    description: "SHA1 of the commit to tag"
    default: ${{ github.sha }}
    required: true
outputs:
  version:
    description: "The version in the Cargo.toml"
  tag_name:
    description: "The name of the generated release"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: box
  color: gray-dark
