name: 'Rust Release'
description: 'Create a github release from version in Cargo.toml on push to main'
inputs:
  cargo_path:
    description: 'Cargo.toml path'
    required: false
    default: 'Cargo.toml'
  body:
    description: 'Text describing the contents of the release'
    required: false
  body_path:
    description: 'Path to file with information about the tag.'
    required: false
  owner:
    description: 'Owner of the repository if it is not the current one'
    required: false
  repo:
    description: 'Repository on which to release.  Used only if you want to create the release on another repo'
    required: false
  dry_run:
    description: 'do not actually create release'
    required: false
    default: false
outputs:
  cargo_version:
    description: 'The version identified from Cargo'
  id:
    description: 'The ID of the created Release'
  tag_name:
    description: 'The tag name of the created Release'
  html_url:
    description: 'The URL users can navigate to in order to view the release'
  upload_url:
    description: 'The URL for uploading assets to the release'
  is_new_release:
    description: 'Flag indicating rather a new release was created or not'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: box
  color: gray-dark
