name: Test Action

on:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "version = \"0.1.0\"" > Cargo.toml
      - uses: ./
        with:
          title: "test"
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: "true"
